version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: tstspring
    environment:
      POSTGRES_DB: tstspring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./prisma:/docker-entrypoint-initdb.d
    networks:
      - korea-mm-guide
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:

networks:
  korea-mm-guide:
    driver: bridge
